/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author acer
 */
public class menuUtama extends javax.swing.JFrame {

    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbHello = new javax.swing.JButton();
        jbEmail = new javax.swing.JButton();
        jbKonversi = new javax.swing.JButton();
        jbKonversi1 = new javax.swing.JButton();
        jbKonversi2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1054, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENU UTAMA");

        jbHello.setBackground(new java.awt.Color(0, 0, 153));
        jbHello.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbHello.setForeground(new java.awt.Color(204, 204, 255));
        jbHello.setText("HELLO WORLD");
        jbHello.setBorder(null);
        jbHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelloActionPerformed(evt);
            }
        });

        jbEmail.setBackground(new java.awt.Color(0, 0, 153));
        jbEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbEmail.setForeground(new java.awt.Color(204, 204, 255));
        jbEmail.setText("VALIDASI EMAIL");
        jbEmail.setBorder(null);
        jbEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmailActionPerformed(evt);
            }
        });

        jbKonversi.setBackground(new java.awt.Color(0, 0, 153));
        jbKonversi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbKonversi.setForeground(new java.awt.Color(204, 204, 255));
        jbKonversi.setText("KONVERSI WAKTU");
        jbKonversi.setBorder(null);
        jbKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKonversiActionPerformed(evt);
            }
        });

        jbKonversi1.setBackground(new java.awt.Color(0, 0, 153));
        jbKonversi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbKonversi1.setForeground(new java.awt.Color(204, 204, 255));
        jbKonversi1.setText("REVERSE KALIMAT");
        jbKonversi1.setBorder(null);
        jbKonversi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKonversi1ActionPerformed(evt);
            }
        });

        jbKonversi2.setBackground(new java.awt.Color(0, 0, 153));
        jbKonversi2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbKonversi2.setForeground(new java.awt.Color(204, 204, 255));
        jbKonversi2.setText("VALIDASI POLINDROM");
        jbKonversi2.setBorder(null);
        jbKonversi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKonversi2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(471, 471, 471))
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbKonversi2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKonversi1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbHello, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jbHello, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbKonversi1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbKonversi2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelloActionPerformed
        this.setVisible(false);
        new helloWorld().setVisible(true);
    }//GEN-LAST:event_jbHelloActionPerformed

    private void jbEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmailActionPerformed
        this.setVisible(false);
        new validasiEmail().setVisible(true);
    }//GEN-LAST:event_jbEmailActionPerformed

    private void jbKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKonversiActionPerformed
        this.setVisible(false);
        new konversiJam().setVisible(true);
    }//GEN-LAST:event_jbKonversiActionPerformed

    private void jbKonversi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKonversi1ActionPerformed
        this.setVisible(false);
        new reverseKalimat().setVisible(true);
    }//GEN-LAST:event_jbKonversi1ActionPerformed

    private void jbKonversi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKonversi2ActionPerformed
        this.setVisible(false);
        new polindrom().setVisible(true);
    }//GEN-LAST:event_jbKonversi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbEmail;
    private javax.swing.JButton jbHello;
    private javax.swing.JButton jbKonversi;
    private javax.swing.JButton jbKonversi1;
    private javax.swing.JButton jbKonversi2;
    // End of variables declaration//GEN-END:variables
}
